language: java
jdk: openjdk11

before_script:
  - wget -q https://fhir.github.io/latest-ig-publisher/org.hl7.fhir.validator.jar -O validator.jar

script:
  - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
  - java -jar validator.jar -version 4.0.0 terminologie
  - java -jar validator.jar -version 4.0.0 datentypen-profile
  - java -jar validator.jar -version 4.0.0 ressourcen-profile
  - java -jar validator.jar -version 4.0.0 beispiele -ig datentypen-profile -ig ressourcen-profile -ig terminologie -recurse
